### ISSUE TITLE
multiActionButton with shinydashboard 

### ISSUE THREAD

**Issue by RB000** [stla/shinyMultiActionButton#2]
Hi , 
I tried to use au multiActionButton with shinydahboard but it changes the colors and the theme of the application .
Before : 
![image](https://user-images.githubusercontent.com/28759682/91834143-f24a2500-ec47-11ea-8054-b83c19757e96.png)

After : 
![image](https://user-images.githubusercontent.com/28759682/91834210-055cf500-ec48-11ea-909f-1126d1a917d9.png)
.
Is there any solution to use a multiActionButton iside a shiny dahsboard sideBar? 
Thank you

**Comment by stla** [comment]
Hello @RB000 

 I'm not familiar with shinyDashboard but I will take a look. Did you try with [shinyMetroUI](https://github.com/RinteRface/shinyMetroUi)? This package also provides the multi action buttons.

**Comment by stla** [comment]
Ah no sorry, the multi action buttons are not implemented in `shinyMetroUI` yet.

**Comment by stla** [comment]
Hello @RB000 

 This is fixed now. For the sidebar, I didn't try yet.

**Comment by stla** [comment]
Yes, this works in the sidebar (in `menuItem` or `menuSubItem`).

**Comment by RB000** [comment]
It works perfectly 👍 
![image](https://user-images.githubusercontent.com/28759682/92096576-55b68d00-edd7-11ea-8fef-3f0a61f0f57d.png)
Thank you.
